Issue #47 Added places API
project-travel-mate/server pull request #107
Opened 2018-07-25 18:42 UTC by techac

# Description

added places api issue #47 

Fixes #47 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `flake8`
- [x] `python manage.py test`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2018-07-27 06:31 UTC, techac commented
@prabhakar267 PR is ready for review

2018-07-28 06:21 UTC, prabhakar267 requested changes

2018-07-28 06:21 UTC, prabhakar267 commented on api/urls.py
> +from api.modules.PlacesAPI import views as places_views
Change module name to `hyperlocal`

2018-07-28 06:21 UTC, prabhakar267 commented on api/modules/PlacesAPI/views.py
> +    except Exception as e:
Have different exceptions for 
+ incorrect / expired API keys
+ throttling error (if possible)

2018-07-28 06:21 UTC, prabhakar267 commented on api/modules/PlacesAPI/constants.py
> +PLACES_API_SEARCH = BASE_URL + 'at={latitude},{longitude}&q={place_keyword}' + '&app_id=' + APP_ID + '&app_code=' + \
`PLACES_SEARCH_API_URL`

2018-07-28 06:21 UTC, prabhakar267 commented on api/modules/PlacesAPI/constants.py
> +BASE_URL = 'https://places.cit.api.here.com/places/v1/autosuggest?'
`PLACES_API_BASE_URL`

2018-07-28 06:21 UTC, prabhakar267 commented on api/modules/PlacesAPI/constants.py
> +APP_ID = os.environ.get("YOUR_APP_ID", "")
use better names than `APP_ID`, `YOUR_APP_ID`, `APP_CODE` and `YOUR_APP_CODE`

2018-07-28 06:21 UTC, prabhakar267 commented on api/modules/PlacesAPI/response.py
> +class PlaceResponse(object):
`HyperlocalResponse`
and filename should be `hyperlocal_response.py`

2018-07-28 06:21 UTC, prabhakar267 commented on api/modules/PlacesAPI/response.py
> +        self.vicinty = kwargs.get('vicinity')
Change name to `address`

2018-07-28 06:21 UTC, prabhakar267 commented on api/modules/PlacesAPI/response.py
> +
Add icon as well

2018-07-28 06:21 UTC, prabhakar267 commented on api/modules/PlacesAPI/views.py
> +            )
Add icon and address

2018-07-29 11:18 UTC, prabhakar267 requested changes

2018-07-29 11:18 UTC, prabhakar267 commented on api/modules/PlacesAPI/views.py
> +    except Exception as e:
If `place_keyword` keyword is incorrect, send an appropriate response

2018-07-29 11:18 UTC, prabhakar267 commented on api/modules/PlacesAPI/views.py
> +    except Exception as e:
If API keys are incorrect or missing, send an appropriate response

2018-08-01 16:32 UTC, techac commented
@prabhakar267 you may review PR

2018-08-01 18:43 UTC, prabhakar267 approved these changes

2018-08-01 18:44 UTC, merged