Checklist APIs created
project-travel-mate/server pull request #154
Opened 2019-02-13 22:57 UTC by BadduCoder

# Description

Checklist and ChecklistItem models have been created to store check list data.
GET and POST APIs have been created. No additional dependencies are required.

**GET** request : _/api/get-checklist_
**POST** request : _/api/add-to-checklist_
                          Accepts one form-data:
                          items : [list of strings separated by comma]

Fixes #46 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [ ] `flake8`
- [x] `python manage.py test`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2019-03-02 02:57 UTC, Swati4star commented
@BadduCoder checks are failing. please look into it.

2019-03-07 11:13 UTC, BadduCoder commented
@Swati4star Please check if everything else is correct.

2019-04-20 12:49 UTC, prabhakar267 requested changes

2019-04-20 12:49 UTC, prabhakar267 commented on api/modules/checklist/views.py
> +        return Response(error_message)
Should be returned with an error code `404`

2019-04-20 12:49 UTC, prabhakar267 commented on api/modules/checklist/views.py
> +        checklist = Checklist.objects.get(user=request.user)
Ignores the order in which items were added.

2019-04-20 12:49 UTC, prabhakar267 commented on api/modules/checklist/model.py
> +class Checklist(models.Model):
What is the need for this Model?
If this serves the purpose of multiple checklists for same user, there should be an option to have name for each checklist and while fetching all items in a checklist, you would have to take input the name/ID of checklist. Also you would need to support an API to a list of all checklists.

2019-04-20 12:49 UTC, prabhakar267 commented on api/modules/checklist/model.py
> +class ChecklistItem(models.Model):
Since this is a "check"list, there needs to be a status. Also you'd need to add two more fields: `created_at` and `last_updated_at`

2019-05-25 06:02 UTC, prabhakar267 commented
Closing due to inactive. 
Feel free to reopen if you decide to work on it.

2019-05-25 06:02 UTC, closed without merging