Token based Authentication
project-travel-mate/server pull request #5
Opened 2018-06-03 19:33 UTC by AnirudhGoel

2018-06-04 04:25 UTC, prabhakar267 requested changes

2018-06-04 04:25 UTC, prabhakar267 commented on api/views.py
> +        return Response(status=status.HTTP_500_INTERNAL_SERVER_ERROR)
Never return 500 response code intentionally from server

2018-06-04 04:25 UTC, prabhakar267 commented on api/views.py
> +    if request.method == 'POST':
Check seems useless

2018-06-04 04:25 UTC, prabhakar267 commented on api/views.py
> +        user=User.objects.create_user(username, email, password)
You can use something like `u = User(email=..., pass=...)`

Reference: https://docs.djangoproject.com/en/dev/topics/db/queries/#creating-objects

2018-06-04 04:25 UTC, prabhakar267 commented on api/views.py
> +    :param fname:
"Params" are all the variables which are present as method parameters
For object structure of any one param, you can use it's description to elaborate more

2018-06-04 04:25 UTC, prabhakar267 commented on api/views.py
> +def signUp(request):
Use PEP8 style method naming
Reference: https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables

2018-06-04 04:25 UTC, prabhakar267 commented on api/views.py
> +    fName = request.POST['fName']
Use `firstname` and `lastname`

2018-06-04 04:25 UTC, prabhakar267 commented on api/views.py
> +def signUp(request):
Also add a check for existing user and send a message accordingly, something like `User with email "xx" already present`

2018-06-08 18:07 UTC, AnirudhGoel commented on api/views.py
> +        user=User.objects.create_user(username, email, password)
Kindly refer to this - https://stackoverflow.com/a/18504852/6229821
User.object.create_user() takes care of setting the password encryption properly.

2018-06-08 18:36 UTC, prabhakar267 approved these changes

2018-06-08 18:37 UTC, prabhakar267 commented
Squash these changes into one commit and update the PR

2018-06-09 19:19 UTC, merged