fix #58 update trip_name
project-travel-mate/server pull request #72
Opened 2018-07-05 18:09 UTC by techac

# Description

Added update trip_name API call

Fixes #58 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?
- [x] `flake8`
- [x] `python manage.py test`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2018-07-05 18:35 UTC, prabhakar267 approved these changes

2018-07-05 18:36 UTC, prabhakar267 requested changes

2018-07-05 18:36 UTC, prabhakar267 commented on api/modules/trips/views.py
> +@api_view(['POST'])
Why is this a POST api?
If you want to make it a post API, change the way you take request parameters

2018-07-06 05:33 UTC, techac commented
@prabhakar267  you may review changes

2018-07-06 05:49 UTC, prabhakar267 approved these changes

2018-07-06 05:49 UTC, merged