Fix #48, added all trip friends
project-travel-mate/server pull request #74
Opened 2018-07-06 10:29 UTC by techac

# Description
Added feature of all trip friends of the authenticated user 

Fixes #48 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `flake8`
- [x] `python manage.py test`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2018-07-06 14:31 UTC, techac commented
you may review the changes now

2018-07-07 10:33 UTC, prabhakar267 requested changes

2018-07-07 10:33 UTC, prabhakar267 commented on api/modules/trips/serializers.py
> +class AllFriendsSerializer(serializers.ModelSerializer):
Have this serializer in User module
Since its a User related information, only our logic is to fetch friends from trips information

2018-07-07 12:58 UTC, techac commented
Requested changes made @prabhakar267  you may review

2018-07-08 07:27 UTC, prabhakar267 requested changes

2018-07-08 07:27 UTC, prabhakar267 commented on api/modules/trips/views.py
> +def trip_friends_all(request):
Please move this method to user views since this is a user related route not a trip related route

2018-07-08 07:27 UTC, prabhakar267 commented on api/modules/trips/views.py
> +    serializer = AllFriendsSerializer(all_trips, many=True)
You can use the `UserSerializer` only  since that allows the client to get user id, name and other information as well

2018-07-08 07:54 UTC, merged