redirected 404 request to home page and the home page to the travel mate website.
project-travel-mate/server pull request #75
Opened 2018-07-07 14:27 UTC by arunikayadav42

redirected 404 request to home page and the home page to the travel mate website.Added a views.py file to the api app and made changes in the urls.py file of the nomad app.

Fixes #41 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `flake8`
- [x] `python manage.py test`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2018-07-07 15:01 UTC, prabhakar267 requested changes

2018-07-07 15:01 UTC, prabhakar267 commented on api/modules/currency/constants.py
> +"""
Remove unwanted files

2018-07-08 07:31 UTC, prabhakar267 requested changes
Please test your code locally, it gives me an error `localhost redirected you too many times.`

2018-07-09 05:23 UTC, prabhakar267 requested changes
404 is not working

2018-07-09 05:23 UTC, prabhakar267 commented on api/views.py
> +    return redirect('http://project-travel-mate.github.io/Travel-Mate/')
Move this URL string to a new file `nomad/constants.py` and name the variable to `URL_NOT_FOUND_REDIRECT`

2018-07-11 07:19 UTC, arunikayadav42 commented
exactly where is the fault now...can you please tell?

2018-07-11 14:36 UTC, prabhakar267 approved these changes

2018-07-11 14:36 UTC, merged