Issue #44, added github api
project-travel-mate/server pull request #85
Opened 2018-07-11 08:49 UTC by techac

# Description

Added GitHub API  for listing issues of a repo

Fixes #44 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `flake8`
- [x] `python manage.py test`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2018-07-11 14:33 UTC, prabhakar267 requested changes

2018-07-11 14:33 UTC, prabhakar267 commented on api/modules/github/views.py
> +                mydict = {k: v for k, v in issue["labels"][i].items() if k in ["name"]}
change the name to something more understandable

2018-07-11 14:33 UTC, prabhakar267 commented on api/modules/github/views.py
> +                labels=tags
I'm getting labels like 
```
        "tags": [
            {
                "name": "gssoc"
            },
            {
                "name": "gssoc-pro"
            },
            {
                "name": "help wanted"
            }
        ]
```
Please change it to a list of strings

2018-07-11 14:33 UTC, prabhakar267 commented on api/modules/github/views.py
> +        api_response = requests.get(GITHUB_API_GET_ISSUES_URL.format(project_name=project))
If I give an incorrect project name, I'm getting `503` with error message `"string indices must be integers"`
Add a better error message with `404` status code

2018-07-12 04:48 UTC, techac commented
@prabhakar267 you may review the changes

2018-07-12 16:18 UTC, prabhakar267 approved these changes

2018-07-12 16:18 UTC, merged